### ISSUE TITLE
SQLite does not support Sum on decimal

### ISSUE THREAD

**Issue by Christoph-Wagner** [TheAxelander/OpenBudgeteer#57]
v1.4 in Debug mode, Windows, SQLite DB

Start app with SQLite, go to Reports.

`System.NotSupportedException` in `ReportViewModel.cs` Line 201
`SQLite cannot apply aggregate operator 'Sum' on expressions of type 'decimal'. Convert the values to a supported type, or use LINQ to Objects to aggregate the results on the client side.`

**Comment by TheAxelander** [comment]
Can confirm this. Will look into it.

**Comment by TheAxelander** [comment]
Should be resolved as part of #58

**Comment by Wijithapaw** [comment]
Still getting this error.
`SQLite cannot apply aggregate operator 'Sum' on expressions of type 'decimal'. Convert the values to a supported type`

Version:
Microsoft.Data.Sqlite.Core 6.0.9
Microsoft.EntityFrameworkCode.Sqlite 6.0.9

I'm using SQLite as an in-memory database in a Unit Test project. So changing the data type is not really an option.
